function DefineTextureEnumArray(gl) {
	TextureEnumArray = [];

	TextureEnumArray[0] = gl.TEXTURE0;
	TextureEnumArray[1] = gl.TEXTURE1;
	TextureEnumArray[2] = gl.TEXTURE2;
	TextureEnumArray[3] = gl.TEXTURE3;
	TextureEnumArray[4] = gl.TEXTURE4;
	TextureEnumArray[5] = gl.TEXTURE5;
	TextureEnumArray[6] = gl.TEXTURE6;
	TextureEnumArray[7] = gl.TEXTURE7;
	TextureEnumArray[8] = gl.TEXTURE8;
	TextureEnumArray[9] = gl.TEXTURE9;
	TextureEnumArray[10] = gl.TEXTURE10;
	TextureEnumArray[11] = gl.TEXTURE11;
	TextureEnumArray[12] = gl.TEXTURE12;
	TextureEnumArray[13] = gl.TEXTURE13;
	TextureEnumArray[14] = gl.TEXTURE14;
	TextureEnumArray[15] = gl.TEXTURE15;
	TextureEnumArray[16] = gl.TEXTURE16;
	TextureEnumArray[17] = gl.TEXTURE17;
	TextureEnumArray[18] = gl.TEXTURE18;
	TextureEnumArray[19] = gl.TEXTURE19;
	TextureEnumArray[20] = gl.TEXTURE20;
	TextureEnumArray[21] = gl.TEXTURE21;
	TextureEnumArray[22] = gl.TEXTURE22;
	TextureEnumArray[23] = gl.TEXTURE23;
	TextureEnumArray[24] = gl.TEXTURE24;
	TextureEnumArray[25] = gl.TEXTURE25;
	TextureEnumArray[26] = gl.TEXTURE26;
	TextureEnumArray[27] = gl.TEXTURE27;
	TextureEnumArray[28] = gl.TEXTURE28;
	TextureEnumArray[29] = gl.TEXTURE29;
	TextureEnumArray[30] = gl.TEXTURE30;
	TextureEnumArray[31] = gl.TEXTURE31;
}
